name: Deploy on Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: Configure Git
        run: |
          git config --local user.email "teplostanski@yandex.ru"
          git config --local user.name "teplostanski"

      - name: Install dependencies
        run: npm install

      - name: Run deploy script
        run: npm run deploy
